# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-01 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='image_name',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
