# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_auto_20190901_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_content', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
