# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_content',
            new_name='comment_content',
        ),
    ]
